Repository Techtonica/techtonica.org, pull requests merged in 2025-03, with the labels that each got.

#637 Add favicon link and move it to the <head> section of your HTML code
  templates/base.html
Labels: bug

#639 Fix Excessive Space Around Demographics Pie Chart on Mobile View
  static/css/style.css
  static/css/style.css.map
  static/js/piechart.js
  static/sass/style.scss
  templates/full-time-program.html
  templates/sponsor.html
Labels: bug

#617 Implement Application Timeline Variables Across Website & Fix Date Formatting (Resolving Issue #517)
  .env.example
  dates.py
  main_site.py
  requirements.in
  requirements.txt
  templates/full-time-program.html
  templates/home.html
  templates/mentor.html
Labels: enhancement, front-end, dependencies, application-automation, 👩🏽‍💻 returning-grad, ⚠️ priority

#668 Issue #587 Ensure Pre-Commit Configuration Stays Updated with Future Python & PIP Upgrades
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/issues_template.yml
  .github/pull_request_template.md
  .pre-commit-config.yaml
  bin/email-teamup-visitors.py
  dates.py
  dev.txt
  main_site.py
  requirements.txt
  static/css/style.css
  static/js/payment-flow.js
  static/js/scroll.js
  static/js/sq-card-pay.js
  static/sass/style.scss
  templates/base.html
  templates/job-form.html
  templates/news.html
  templates/testimonials.html
Labels: bug, dependencies, 👩🏽‍💻 returning-grad, ⚠️ priority

#652 Remove Bypass Codes # noqa: E501 & Format Code Lines > 79 characters (Resolving Issue #651)
  .pre-commit-config.yaml
  dates.py
  main_site.py
Labels: enhancement, dependencies, 👩🏽‍💻 returning-grad

#666 Update newsletter signup link in volunteer template
  templates/volunteer.html
Labels: bug

#664 Create CSS/SCSS Styling Instructions Wiki
  README.md
Labels: enhancement, 👩🏽‍💻 returning-grad

#709 Staging DB not connecting - connection string not formatted correctly Resolving Issue #667
  .gitignore
  .pre-commit-config.yaml
  bin/email-teamup-visitors.py
  db_connection.py
  main_site.py
  templates/full-time-program.html
Labels: bug, back-end, 👩🏽‍💻 returning-grad

#615 Accessibility Enhancements for Application Form
  .gitignore
  .pre-commit-config.yaml
  README.md
  bin/email-teamup-visitors.py
  dates.py
  db_connection.py
  main_site.py
  static/css/style.css
  templates/app-additional.html
  templates/app-form-admin.html
  templates/app-form-details.html
  templates/app-form.html
  templates/app-household.html
  templates/app-long-text.html
  templates/app-questionnaire.html
  templates/app-reference.html
  templates/base.html
  templates/full-time-program.html
  templates/job-form.html
Labels: enhancement, 👩🏽‍💻 returning-grad

#724 Add Width Styling to Application Form Fieldsets
  templates/app-additional.html
  templates/app-form-admin.html
  templates/app-form.html
  templates/app-household.html
  templates/app-long-text.html
  templates/app-questionnaire.html
  templates/app-reference.html
Labels: bug, application-automation, 👩🏽‍💻 returning-grad

#726 Standardize Legend Font Sizes in Fieldsets Across Application Forms
  templates/app-additional.html
  templates/app-form-admin.html
  templates/app-form.html
  templates/app-household.html
  templates/app-long-text.html
  templates/app-questionnaire.html
  templates/app-reference.html
Labels: bug, front-end, application-automation, 👩🏽‍💻 returning-grad
