Repository Techtonica/techtonica.org, pull requests merged in 2025-04, with the labels that each got.

#738 Create Wiki for .Env File Resolving Issue #702
  .env.example
  README.md
Labels: enhancement, application-automation, 👩🏽‍💻 returning-grad

#728 Replace Sponsors Table and Footer Icons with SVGs
  static/css/style.css
  static/css/style.css.map
  static/sass/style.scss
  templates/base.html
  templates/sponsor.html
Labels: enhancement, front-end, 👩🏽‍💻 returning-grad

#748 Remove un-used MVP starter code
  application_process.py
  course_management.py
  main_site.py
  models.py
  templates/application/dashboard.html
  templates/application/form.html
  templates/course/detail.html
  templates/course/list.html
Labels: enhancement, 👩🏽‍💻 returning-grad

#746 Local Docker setup needs updating / fixing Resolving Issue #510
  .dockerignore
  Dockerfile
  docker-compose.yaml
Labels: bug, enhancement, back-end, dependencies, 👩🏽‍💻 returning-grad, ⚠️ priority
