Repository Techtonica/techtonica.org, pull requests merged in 2025-02, with the labels that each got.

#561 Updated README with Local Set Up Instructions for Prettier Plug-In - Issue #498
  README.md
Labels: dependencies, 👩🏽‍💻 returning-grad

#538 Create template for application form and form details pages
  main_site.py
  templates/app-form-details.html
  templates/app-form.html
Labels: enhancement

#565 Updated Black to v24.8.0, Click to v8.1.8 Resolving Issue #525
  .pre-commit-config.yaml
Labels: dependencies, 👩🏽‍💻 returning-grad

#578 FAQ Page Enhancements
  templates/faqs.html
Labels: bug, 👩🏽‍💻 returning-grad

#613 Merged all timeline variables to one file resolving issue #517
  dates.py
Labels: enhancement, application-automation, 👩🏽‍💻 returning-grad

#612 Increase Sponsor Icon Size for Mobile Readability
  static/css/style.css
  static/css/style.css.map
  static/sass/style.scss
  templates/home.html
  templates/sponsor.html
Labels: front-end
